### ISSUE TITLE
discuss: raft

### ISSUE THREAD

**Issue by fern4lvarez** [oscillatingworks/compass#3]
https://github.com/oscillatingworks/compass/tree/master/raft

**Comment by fern4lvarez** [comment]
Not that a dislike the idea of getting into Haskell (an old friend from my university years) or working with protocols for distributed systems, but I see some importabt cons on this kind of projects:
- It's a protocol implementation, you cannot really make the difference compared to other implementations or offer something new and better, you have to stick to the specification.
- It's a Haskell library, so only Haskell devs can use it, reducing drastically the number of potential user that can get interest.

**Comment by mkorszun** [comment]
True. Actually if we would decide for this protocol I would opt for erlang or scala implementation which are more mature and popular.
